### ISSUE TITLE
Does not build using GCC 8.2.1

### ISSUE THREAD

**Issue by skade** [Vantiq/vantiq-sdk-micro#1]
Using stock GCC 8.2.1 on Fedora 29, the library doesn't build properly as it runs into warning and all warnings are treated as errors:

```
[skade@Nostalgia-For-Infinity vme]$ gcc --version
gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
[skade@Nostalgia-For-Infinity vme]$ make
gcc -g -Wall -Werror -std=gnu99 -O2 -fPIC   -c -o vantiq_client.o vantiq_client.c
vantiq_client.c: In function ‘vc_init’:
vantiq_client.c:272:9: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
         strncpy(vc->server_url, url, len-1);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vantiq_client.c:268:18: note: length computed here
     size_t len = strlen(url);
                  ^~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: vantiq_client.o] Error 1
```
