### PR TITLE
compatibility with gcc 8.2+ and fix for header name case

### LINKED ISSUE #1: Does not build using GCC 8.2.1
Using stock GCC 8.2.1 on Fedora 29, the library doesn't build properly as it runs into warning and all warnings are treated as errors:

```
[skade@Nostalgia-For-Infinity vme]$ gcc --version
gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
[skade@Nostalgia-For-Infinity vme]$ make
gcc -g -Wall -Werror -std=gnu99 -O2 -fPIC   -c -o vantiq_client.o vantiq_client.c
vantiq_client.c: In function ‘vc_init’:
vantiq_client.c:272:9: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
         strncpy(vc->server_url, url, len-1);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vantiq_client.c:268:18: note: length computed here
     size_t len = strlen(url);
                  ^~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: vantiq_client.o] Error 1
```

### LINKED ISSUE #2: header property names may be upper or lower case
have to do case insensitive comparisons when looking for them in the response.

### PR DESCRIPTION
**Pull request by mer2github**
Closes #1 
Closes #2

### CODE REVIEW

File: src/vmeTest/config.properties [hunk 1]
```diff
@@ -2,5 +2,5 @@
 #DPIPORT = 3490
 DPISOCKETPATH = /tmp/vipo_socket
 VANTIQ_BASEURL = https://dev.vantiq.com
-VANTIQTOKEN = KtaUNyWsplL-a6Lujaghp7Ky7_v4JfI1Et7LQLunwqI=
-#LOG_LEVEL = DEBUG
+VANTIQTOKEN = <replace with Vantiq access token>
+# LOG_LEVEL = DEBUG
```
Comment (sfitts) [inline src/vmeTest/config.properties:6]: Out of curiosity -- why the extra space

**Review by sfitts — APPROVED** [review]
LGTM

File: src/vmeTest/config.properties (hunk 1 above)
Comment (mer2github) [reply src/vmeTest/config.properties:6]: inadvertent. i enabled then commented out again with an extra space. thx for looking over the changes.
